### ISSUE TITLE
Squad en role data 

### ISSUE THREAD

**Issue by Ryank2004** [SamaraFellaDina/connect-your-tribe-squad-page#4]
``` html
<ul>
    <% persons.forEach(person => {
      if(person.squad_id === 3 && person.role.includes("member")) { %>
        <li><a href="./person/<%= person.id %>"><%= person.name %></a>, id <%= person.id %>, squad_id <%= person.squad_id %>
        </li>
      <% }
    }) %>
  </ul>

```

Met deze code kan je kiezen van welke personen je de data wilt ontvangen. Hier zie je dat ik alle personen met squad id 3 wil en  met een member role.

member moet tussen haakjes, omdat het een array is. Dat zie aan hoe het in de database word laten zien. 
Arrays gebruiken [ ].

**Comment by SamaraFellaDina** [comment]
Wajow thanks! ik kan wel huilen om deze code maar hier heb je me echt mee verder geholpen. Thanks!

Ik heb de code alleen net een beetje anders dan jij. Ik denk dat wij allebei iets anders hebben bij `server.js`.


```html
<ul>
    <% data.forEach(person => {
        if(person.squad_id === 3 && person.role.includes("member")) { %>
          <li><a href="./person/<%= person.id %>"><%= person.name %></a>
            %>
          </li>
        <% }
      }) %>
    </ul>
```
Ik heb `data` ipv `persons`. Ik weet daarom niet wat je hebt gedaan daar, maar als jij het wel weet hoor ik het graag :)

**Comment by SamaraFellaDina** [comment]
https://github.com/SamaraFellaDina/connect-your-tribe-squad-page/commit/6db8de800312ce6e1ab94ff22e9d47590c0a5528
