### ISSUE TITLE
Zorg dat er een placeholder `<img>` wordt geplaatst

### ISSUE THREAD

**Issue by SamaraFellaDina** [SamaraFellaDina/connect-your-tribe-squad-page#5]
![image](https://github.com/SamaraFellaDina/connect-your-tribe-squad-page/assets/144009778/3068370c-6410-4bab-8a0c-689d22ab4d4d)

**Comment by SamaraFellaDina** [comment]
```js
function insertPlaceholder() {
    const placeHolderImage = "assets/images/placeholder.jpg";
    const imageElement = document.getElementById('profile-image');
    
    if (imageElement) {
        imageElement.src = placeHolderImage; // Set src to placeholder image URL
    }
}

const elements = document.querySelectorAll('.profile');
const count = elements.length;
console.log(count);
```

 Ik heb al een beetje code gebruikt, alleen weergeeft hij dit alleen op de eerste persoon op de pagina. Zelfs als die persoon al een file heeft

![image](https://github.com/SamaraFellaDina/connect-your-tribe-squad-page/assets/144009778/c6819d47-553a-436a-b085-7b4855847909)

**Comment by SamaraFellaDina** [comment]
Na heel wat uit testen en proberen, heb ik meer geleerd over het `onerror` command in het image element

```html
              <img 
              src="<%= person.avatar %>" 
              alt="profiel" id="profile-image" 
              onerror="this.onerror=null; this.src='assets/images/placeholder.jpg'"
              >
```
Dit is uiteindelijk de code die me verder heeft geholpen, alleen weet ik niet of het beter is om een referentie naar de `js` te maken, maar hij werkt in ieder geval wel :)

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOWNyNG03eHo4cm9hb3BhaWwwejBiZjlxMWRkeTRiYmVmc2Q4cGRxNCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3ohzdIuqJoo8QdKlnW/giphy.gif)

# Maar hoe werkt de code?

**Comment by SamaraFellaDina** [comment]
https://github.com/SamaraFellaDina/connect-your-tribe-squad-page/commit/45ee984e2b2d371819e79450b69a3eb9683960f8

**Comment by SamaraFellaDina** [comment]
@christoph3r3w

**Comment by SamaraFellaDina** [comment]
https://github.com/lisagjh/connect-your-tribe-squad-page/blob/0ee6c0e814f2570ac9dddc78af018ae534d8cb5d/views/index.ejs#L29-L30

Kijk anders naar deze code :)

**Comment by SamaraFellaDina** [comment]
Aangepast!

```html
              <img 
              src="<%= (person.avatar == '') ? 'assets/placeholder.jpg' : person.avatar %>"
              alt="profiel" 
              onerror="this.src='/assets/images/placeholder.jpg'"
              >
```

**Comment by christoph3r3w** [comment]
belated, but thanks for the tips
